apiVersion: v1
kind: Service
metadata:
  name: knowledge-service
  labels:
    app: knowledge
spec:
  selector:
    app: knowledge
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: knowledge
  template:
    metadata:
      labels:
        app: knowledge
    spec:
      containers:
      - name: knowledge-container
        image: knowledge
        ports:
        - containerPort: 3000
